name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  genkey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore redup.keystore \
            -alias ${{ secrets.KEY_ALIAS }} \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ secrets.STORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "CN=Redup, OU=App, O=Awiselow, L=ID, S=ID, C=ID"

      - name: Convert to Base64
        run: base64 redup.keystore | tr -d '\n' > redup_keystore_base64.txt

      - uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: redup_keystore_base64.txt
